version: 2.1

orbs:
  python: circleci/python@0.3.2
  k3d: devopsspiral/k3d@0.1.2
jobs:
  build-and-test:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test
  test-on-k8s:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Kubelibrary container image
          command: |
            docker build -t kubelibrary -f testcases/Dockerfile .
      - k3d/k3d-helpers
      - k3d/k3d-up:
          cluster-name: testk3d
      - k3d/k3d-run:
          step-name: Run kubectl
          command: |
            helm repo add stable https://kubernetes-charts.storage.googleapis.com
            # git clone https://github.com/kyma-incubator/octopus
            # docker cp octopus repo:/repo/
            # helm install octopus /repo/octopus/chart/octopus/
            helm install grafana stable/grafana -f /repo/testcases/grafana/values.yaml
            sleep 30
            docker --rm run -t kubelibrary \
            -e KLIB_POD_PATTERN='grafana.*' \
            -e KLIB_POD_ANNOTATIONS='{"checksum/config":"3bb97e1695589c9bcdf6a6cd10c03517286ab7697626e6f02dd6fb2bc4a27796"}' \
            -e KLIB_POD_NAMESPACE=default \
            -i grafana /root/testcases/
      - k3d/k3d-down:
          cluster-name: testk3d
workflows:
  main:
    jobs:
      - build-and-test
      - test-on-k8s
  #     - test-coverage
  #     - code-quality
  # publish:
  #   jobs:
  #     - publish-to-pypi