version: 2.1

orbs:
  python: circleci/python@1.0.0

workflows:
  main:
    jobs:
      - python/test
  #     - test-on-k8s
  #     - test-coverage
  #     - code-quality
  # publish:
  #   jobs:
  #     - publish-to-pypi